import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Swal from "sweetalert2/dist/sweetalert2.js";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body
          suppressHydrationWarning={true}
          className="min-h-screen bg-slate-100"
        >
          {children}
        </body>
      </html>
    </Provider>
  );
}
